apiVersion: v1
kind: Service
metadata:
  name: demo-app-lb
  namespace: satish
  labels:
    app: demo-app
    environment: development
    project: demo
spec:
  type: LoadBalancer
  selector:
    app: demo-app
    environment: development
    project: demo
  ports:
    - port: 80
      targetPort: 80