apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  namespace: satish
  labels:
    app: demo-app
    environment: development
    project: demo
spec:
  containers:
    - name: demo-app
      image: nginx:latest
      ports:
        - containerPort: 80